#!/bin/bash
#
# Installation script for spell-check
# spell-check and autocorrect large documents and files
#
# Copyright (C)   2016    Madhav Datt
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#

# Move spell-check to /etc
cd /etc
mkdir spell-check
mv ~/Downloads/spell-check/* /etc/spell-check
cd /etc/spell-check

# Add permanent aliases for scripts
cat aliases.txt >> ~/.bash_aliases
. ~/.bashrc

# Clean downloaded folders
rm -rf ~/Downloads/spell-check

# Compile C source code
cd src
make
