#!/bin/bash
#
# Installation script for spell-check
# spell-check and autocorrect large documents and files
#
# Copyright (C)   2016    Madhav Datt
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
#

# Move spell-check to /opt
mkdir /opt/spell-check
mv $1/spell-check/* /opt/spell-check
cd /opt/spell-check

# Add permanent aliases for scripts
cat aliases.txt >> ~/.bash_aliases
. ~/.bashrc

# Compile C source code
cd src
make
